name: Build Cassandra Connector

on:
  push:
    paths:
      - 'pom.xml'
      - 'debezium-connector-cassandra/**'
  pull_request:
    paths:
      - 'pom.xml'
      - 'debezium-connector-cassandra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Setup Debezium Parent
        run : git clone https://github.com/debezium/debezium.git $PWD/core-repo && cd $PWD/core-repo && mvn -B clean install -DskipTests -DskipITs -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn && cd $OLDPWD
      - name: Check changes in Debezium Connector Cassandra
        run: mvn clean install -am -pl debezium-connector-cassandra

